# Generated by Django 3.1.5 on 2021-11-24 04:42

from django.db import migrations, models
import django.db.models.deletion
import unagaapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_To_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'add_to_cart',
            },
        ),
        migrations.CreateModel(
            name='Arrivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_img', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('arrival_content', models.TextField(null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arrivals',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=120, null=True)),
                ('banner_image1', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('banner_image2', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('banner_image3', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('banner_image4', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('banner_image5', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('banner_content', models.TextField(null=True)),
                ('banner_url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_category', models.CharField(max_length=120, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, null=True)),
                ('customer_email', models.EmailField(max_length=150, null=True)),
                ('customer_subject', models.CharField(max_length=150, null=True)),
                ('customer_comments', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'customer_contact',
            },
        ),
        migrations.CreateModel(
            name='Customer_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=150, null=True)),
                ('customer_email', models.EmailField(max_length=150, null=True)),
                ('customer_password', models.CharField(max_length=150, null=True)),
                ('customer_confirm_password', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'customer_register',
            },
        ),
        migrations.CreateModel(
            name='Damaged_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, null=True)),
                ('product_code', models.IntegerField(null=True)),
                ('categories', models.CharField(max_length=100, null=True)),
                ('sub_categories', models.CharField(max_length=100, null=True)),
                ('unit_price', models.CharField(max_length=10, null=True)),
                ('purchase_price', models.CharField(max_length=10, null=True)),
                ('total_quantity', models.CharField(max_length=10, null=True)),
                ('damaged_quantity', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Damages',
            },
        ),
        migrations.CreateModel(
            name='Left_Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftbanner_name', models.CharField(max_length=120, null=True)),
                ('leftbanner_image1', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('leftbanner_image2', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('leftbanner_content', models.TextField(null=True)),
                ('leftbanner_url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'left_banner',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, null=True)),
                ('mobile_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=120, null=True)),
                ('product_code', models.CharField(max_length=10, null=True)),
                ('ref_no', models.CharField(max_length=10, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('purchase_price', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, null=True)),
                ('product_code', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('categories', models.CharField(max_length=100, null=True)),
                ('sub_categories', models.CharField(max_length=100, null=True)),
                ('fabric', models.CharField(max_length=100, null=True)),
                ('work', models.CharField(max_length=100, null=True)),
                ('fabric_care', models.CharField(max_length=100, null=True)),
                ('variant_color', models.CharField(max_length=100, null=True)),
                ('sizes', models.CharField(max_length=10, null=True)),
                ('unit_price', models.CharField(max_length=10, null=True)),
                ('purchase_price', models.CharField(max_length=10, null=True)),
                ('tax', models.CharField(max_length=10, null=True)),
                ('gst', models.CharField(max_length=10, null=True)),
                ('discount', models.CharField(max_length=10, null=True)),
                ('total_quantity', models.CharField(max_length=10, null=True)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('image2', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('image3', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('image4', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Right_Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightbanner_name', models.CharField(max_length=120, null=True)),
                ('rightbanner_image1', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('rightbanner_image2', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('rightbanner_content', models.TextField(null=True)),
                ('rightbanner_url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'right_banner',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_category', models.CharField(max_length=120, null=True)),
                ('sub', models.CharField(max_length=120, null=True)),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('product_name', models.CharField(max_length=120, null=True)),
                ('categories', models.CharField(max_length=100, null=True)),
                ('sub_categories', models.CharField(max_length=100, null=True)),
                ('select_branch1', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=10, null=True)),
                ('select_branch2', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'transfer',
            },
        ),
        migrations.CreateModel(
            name='Unaga_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, null=True)),
                ('user_mobile', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_username', models.CharField(max_length=120, null=True)),
                ('user_password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'unaga_user',
            },
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, null=True)),
                ('mobile_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('alt_mobile', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('no_dressess', models.CharField(max_length=120, null=True)),
                ('images', models.FileField(blank=True, null=True, upload_to=unagaapp.models.filepath)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('wardrobe_no', models.CharField(max_length=120, null=True)),
                ('reciever_name', models.CharField(max_length=120, null=True)),
            ],
            options={
                'db_table': 'wardrobe',
            },
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('clast', models.CharField(max_length=100)),
                ('caddress', models.CharField(max_length=300)),
                ('caddress2', models.CharField(max_length=100)),
                ('ccity', models.CharField(max_length=100)),
                ('cstate', models.CharField(max_length=100)),
                ('cpin', models.IntegerField()),
                ('cphone', models.IntegerField()),
                ('cemail', models.CharField(max_length=100)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unagaapp.product')),
                ('total_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unagaapp.add_to_cart')),
            ],
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unagaapp.product'),
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unagaapp.customer_register'),
        ),
        migrations.CreateModel(
            name='add_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_qty', models.IntegerField(null=True)),
                ('prod_qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unagaapp.product')),
            ],
        ),
    ]
