# Generated by Django 3.1.5 on 2021-11-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unagaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unagaapp.add_to_cart')),
            ],
        ),
    ]
